# Generated by Django 4.2.16 on 2024-12-05 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=50)),
                ('description_service', models.CharField(max_length=100)),
                ('price_service', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Additional_service_cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=50)),
                ('price_service', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cabin', models.CharField(max_length=50)),
                ('description_cabin', models.CharField(max_length=500)),
                ('capacity', models.IntegerField()),
                ('count_free', models.IntegerField()),
                ('number_cabin', models.IntegerField()),
                ('price', models.IntegerField()),
                ('photo_cabin', models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Cabin')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cruise', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('passport_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_port', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ship', models.CharField(max_length=50)),
                ('image_ship', models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Ship')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('count_cabins', models.IntegerField()),
                ('year_of_release', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('engine_power', models.IntegerField()),
                ('description_ship', models.CharField(max_length=500)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ship')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_day', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('description_route', models.CharField(max_length=100)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cruise')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.port')),
            ],
        ),
        migrations.CreateModel(
            name='Place_cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_place', models.ImageField(upload_to='')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cabin')),
            ],
        ),
        migrations.AddField(
            model_name='cruise',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ship'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ship'),
        ),
        migrations.CreateModel(
            name='Booking_ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_booking', models.UUIDField(default=uuid.UUID('fb1ac12a-d0ba-4904-b817-a98dda95debc'), editable=False)),
                ('count_day', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.additional_service')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_period', models.IntegerField()),
                ('rental_price', models.IntegerField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ship')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('price', models.IntegerField()),
                ('date_booking', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('additional_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.additional_service_cruise')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cruise')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger')),
                ('place_cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.place_cabin')),
            ],
        ),
    ]
