# Generated by Django 4.2.16 on 2024-12-06 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_booking_ship_number_booking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additional_service',
            options={'verbose_name': 'Дополнительные услуги', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='additional_service_cruise',
            options={'verbose_name': 'Дополнительные услуги на крумзе', 'verbose_name_plural': 'Дополнительные услуги на крумзе'},
        ),
        migrations.AlterModelOptions(
            name='booking_cruise',
            options={'verbose_name': 'Бронирование билета на круиз', 'verbose_name_plural': 'Бронирование билета на круиз'},
        ),
        migrations.AlterModelOptions(
            name='booking_list',
            options={'verbose_name': 'Сведения аренды лодки', 'verbose_name_plural': 'Сведения аренды лодки'},
        ),
        migrations.AlterModelOptions(
            name='booking_ship',
            options={'verbose_name': 'Аренда лодок', 'verbose_name_plural': 'Аренда лодок'},
        ),
        migrations.AlterModelOptions(
            name='cabin',
            options={'verbose_name': 'Каюта', 'verbose_name_plural': 'Каюта'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='cruise',
            options={'verbose_name': 'Круизы', 'verbose_name_plural': 'Круизы'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Пассажиры', 'verbose_name_plural': 'Пассажиры'},
        ),
        migrations.AlterModelOptions(
            name='place_cabin',
            options={'verbose_name': 'Место в каюте', 'verbose_name_plural': 'Место в каюте'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': 'Порт', 'verbose_name_plural': 'Порт'},
        ),
        migrations.AlterModelOptions(
            name='routes',
            options={'verbose_name': 'Маршруты', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='ship',
            options={'verbose_name': 'Корабли', 'verbose_name_plural': 'Корабли'},
        ),
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name': 'Характеристики', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('2525c722-5ed1-4362-b1eb-95396c681463'), editable=False),
        ),
    ]
