# Generated by Django 4.2.16 on 2024-12-14 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_booking_ship_number_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('b0aba537-5655-4ef5-aaa4-7c47b0a2d367'), editable=False),
        ),
        migrations.AlterField(
            model_name='routes',
            name='port',
            field=models.ForeignKey(default='День в море', on_delete=django.db.models.deletion.CASCADE, to='myapp.port'),
        ),
    ]
