# Generated by Django 4.2.16 on 2024-12-15 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_booking_ship_number_booking_alter_routes_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('328b749c-c67b-4a26-8735-6c7c3be78d4d'), editable=False),
        ),
        migrations.AlterField(
            model_name='routes',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.port'),
        ),
    ]
