# Generated by Django 4.2.16 on 2024-12-15 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booking_ship_number_booking_alter_routes_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='arrival_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='routes',
            name='departure_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('b74c110f-57ab-4873-91f8-59dd17625983'), editable=False),
        ),
        migrations.AlterField(
            model_name='routes',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
