# Generated by Django 4.2.16 on 2024-12-15 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_routes_arrival_date_routes_departure_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='arrival_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='departure_date',
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('dd7156ea-51f3-420e-8e30-9b4da9ca299b'), editable=False),
        ),
    ]
