# Generated by Django 4.2.16 on 2024-12-17 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cabin_range_end_cabin_range_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('0f0b44e3-60e4-4baa-8ded-48b62fb87950'), editable=False),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Вместимость каюты'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='count_free',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество свободных кают'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='description_cabin',
            field=models.TextField(max_length=1000, verbose_name='Описание каюты'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='range_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Конечный номер каюты'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='range_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Начальный номер каюты'),
        ),
    ]
