# Generated by Django 4.2.16 on 2024-12-17 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_alter_booking_ship_number_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('45cf6f99-7ee6-4026-81ae-88d6ec2ff9c4'), editable=False),
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
