# Generated by Django 4.2.16 on 2024-12-17 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_alter_booking_ship_number_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_cruise',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('4fd04a37-e416-4858-bea4-a2e2cb687223'), editable=False),
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger'),
        ),
    ]
