# Generated by Django 4.2.16 on 2024-12-18 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_booking_cruise_passenger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_cruise',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger'),
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('f8aaaeb8-c6df-4aed-a2bc-3773e0e8af4d'), editable=False),
        ),
    ]
