# Generated by Django 4.2.16 on 2024-12-18 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_booking_cruise_passenger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='ship',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cruise',
            name='count_night',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('e2fd5142-e09d-48e8-a900-17961282ac26'), editable=False),
        ),
        migrations.CreateModel(
            name='Date_cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('period', models.PositiveIntegerField()),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cruise')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ship')),
            ],
            options={
                'verbose_name': 'Дата круиза',
                'verbose_name_plural': 'Дата круиза',
            },
        ),
    ]
