# Generated by Django 4.2.16 on 2024-12-18 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_cruise_end_date_remove_cruise_ship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('252b8695-f826-47e4-9a44-ec8de15fbfb1'), editable=False),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='count_night',
            field=models.PositiveIntegerField(),
        ),
    ]
