# Generated by Django 4.2.16 on 2024-12-18 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_booking_ship_number_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_ship',
            name='number_booking',
            field=models.UUIDField(default=uuid.UUID('e4c28196-5655-4b71-a74d-a8e289362c50'), editable=False),
        ),
    ]
